name: default-variable
on: push
jobs:
  test:
   runs-on: self-hosted
   steps:
     - name: print Repo name
       run: echo "This repo name is $GITHUB_REPOSITORY"

     - name: workflow name
       run: echo "This workflow name is $GITHUB_WORKFLOW"
     
  
