name: input-workflow

on:
  workflow_dispatch:
    inputs:
      num1:
        description: "Enter first number"
        required: true
      num2:
        description: "Enter second number"
        required: true

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Add numbers
        run: echo "Sum = $((${{ inputs.num1 }} + ${{ inputs.num2 }}))"
